import type { Metadata } from "next";
import { Golos_Text } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/provider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";

const inter = Golos_Text({
  subsets: ["cyrillic"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-[#080808]", inter.className)}>
        <Providers>
          <div className="">{children}</div>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
